---
- hosts: nginx
  become:  true
  gather_facts: no

  roles:
    - { role: http, php_fpm_ip: 51.250.92.58, php_fpm_port: 9000 }
    - { role: users, user_to_create: user1 }

- hosts: php
  become: true
  gather_facts: no

  roles:
    - { role: php, php_fpm_port: 9000 }
    - { role: users, user_to_create: user1 }