---
- name: Setup Postfix
  hosts: debian
  become: yes
  gather_facts: yes
  tags: init postfix

  tasks:
  - name: Configure postfix hostname
    ansible.builtin.debconf:
      name: postfix
      question: postfix/mailname
      vtype: string
      value: "{{ansible_hostname}}.com"

  - name: Configure postfix main_mailer_type
    ansible.builtin.debconf:
      name: postfix
      question: postfix/main_mailer_type
      vtype: select
      value: Internet site

  - name: Install postfix package
    ansible.builtin.apt:
      name: postfix
      state: present

  - name: Ensure postfix service is running
    ansible.builtin.systemd:
      name: postfix
      state: started

- name: Remove postfix and its config files
  hosts: debian
  become: yes
  gather_facts: no
  tags: drop postfix

  tasks:
  - name: Remove postfix and purge its config
    ansible.builtin.apt:
      name: postfix
      state: absent
      purge: yes
